spring:
  application:
    name: open_notepad
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
  datasource:
    url: jdbc:mysql://localhost:3306/pacipapadb
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
 